#ifndef SLIMDRIVESYSTEMDEFINES_H_
#define SLIMDRIVESYSTEMDEFINES_H_



#define FLASH_DEFAULT_CONFIGURATION 1

//Hardware Maximum Capacity Definition.

//pressure sensor
#define SLIMDRIVE_PRESSURE_MAX 24

//chamber
#define SLIMDRIVE_CHAMBER_MAX 24


//imu and unijoint
#define SLIMDRIVE_IMUNIJOINTBOARD_MAX 6

//valve board
#define SLIMDRIVE_VALVE_MAX 48

#define SLIMDRIVE_PUMP_MAX 2


//segment
#define SLIMDRIVE_SEGMENT_MAX 6//

#define SLIMDRIVE_SEGMENT_CHAMBER_MAX 4//

//Gripper
#define GRIPPER_CHAMBER_MAX 4


//ARM
#define SLIMDRIVE_ARM_MAX 6

#define ARM_ACTION_MAX 4

#define ARM_KE_JOINT_MAX 10

#define PI_f 3.14159265358f


#define MAX_CUSTOM_INPUTOUTPUT_NUM  16

#define SOFTSEGMENT_LIBSIZE 1280

#define BANK_ADD_BITS 3
#define FIELD_ADD_BITS 4
#define ITEM_ADD_BITS 9

#define SD_PLATFORM_REG_ADDRESS_BANK_MASK 0xE000
#define SD_PLATFORM_REG_ADDRESS_FIELD_MASK 0x1E00
#define SD_PLATFORM_REG_ADDRESS_ITEM_MASK 0x01FF

#define __SD_GET_BANK_ADDRESS(x)  (uint16_t)((x & SD_PLATFORM_REG_ADDRESS_BANK_MASK)>>(16-BANK_ADD_BITS))
#define __SD_GET_FIELD_ADDRESS(x) (uint16_t)((x & SD_PLATFORM_REG_ADDRESS_FIELD_MASK)>>(16-BANK_ADD_BITS-FIELD_ADD_BITS))
#define __SD_GET_ITEM_ADDRESS(x)  (uint16_t)((x & SD_PLATFORM_REG_ADDRESS_ITEM_MASK))

#define BANK_NUM_MAX (1<<BANK_ADD_BITS)
#define FIELD_NUM_MAX  (1<<FIELD_ADD_BITS)



#endif /* SLIMDRIVESYSTEMDEFINES_H_ */
